### ISSUE TITLE
Variables, maps, and functions

### ISSUE THREAD

**Issue by yourpalsonja** [Shopify/css#20]
Update the Variables, maps, and functions section!

### Todos:

- [ ] Add information about tokens?
- [ ] Add information about maps and functions? Do we use functions much?
- [ ] Create a `2020-update_variables-maps-functions` branch

### Questions
- Right now, there is only info about variables, do we need to change the name of this section? We should probably also add some information about using CSS variables. Does the information about `maps` and `functions` belong here, or could it live with information about `mixins` in another section?
- How is the colour system that's being rolled out going to affect this? @AndrewMusgrave @dleroux  we need your insight here!

**Comment by AndrewMusgrave** [comment]
> How is the colour system that's being rolled out going to affect this?

Probably a lot. Tokens are going to be super important moving forward. Polaris is deprecating the public sass API (where most of the UI mixins/functions live). And tokens will be the source of truth.

Polaris uses functions quite a lot for base for core utilities, like spacing, z-index, etc. Mixins are pretty big as well for sharing common styling patterns such as typography or button styles.

Consuming projects don't really use them a lot though. For example in web only one custom function is being used, and it's to return the result of a map (ignoring a few functions that we're copied over from resource list).

Mixins are used more often, however still infrequently. Having some solid guidelines on them might increase awareness and adaptation.
